"""Static checks of the deploy artefacts (Dockerfile, deploy/*.yaml, docs/DEPLOY.md). Offline, no cluster needed."""
from __future__ import annotations

import re
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parent.parent
DEPLOY = ROOT / "deploy"


def _load(name: str) -> list[dict]:
    with (DEPLOY / name).open(encoding="utf-8") as fh:
        return [d for d in yaml.safe_load_all(fh) if d]


def _one(name: str, kind: str) -> dict:
    docs = [d for d in _load(name) if d.get("kind") == kind]
    assert len(docs) == 1, f"{name}: expected exactly one {kind}"
    return docs[0]


def _all_docs() -> list[dict]:
    docs: list[dict] = []
    for path in sorted(DEPLOY.glob("*.yaml")):
        docs.extend(_load(path.name))
    return docs


@pytest.fixture(scope="module")
def deployment() -> dict:
    return _one("deployment.yaml", "Deployment")


@pytest.fixture(scope="module")
def container(deployment) -> dict:
    containers = deployment["spec"]["template"]["spec"]["containers"]
    assert len(containers) == 1
    return containers[0]


def _env(container: dict) -> dict[str, str]:
    return {e["name"]: e["value"] for e in container["env"] if "value" in e}


def test_every_deploy_file_parses_and_has_a_kind():
    files = sorted(DEPLOY.glob("*.yaml"))
    names = {p.name for p in files}
    assert {
        "deployment.yaml", "service.yaml", "ingress.yaml", "pvc.yaml",
        "secret.example.yaml", "servicemonitor.yaml", "cronjob.yaml",
    } <= names
    for path in files:
        docs = _load(path.name)
        assert docs, f"{path.name} is empty"
        for doc in docs:
            assert doc.get("apiVersion") and doc.get("kind") and doc.get("metadata", {}).get("name")


def test_manifests_are_namespace_less():
    docs = _all_docs()
    assert docs
    for doc in docs:
        assert "namespace" not in doc["metadata"], f"{doc['kind']}/{doc['metadata']['name']} sets a namespace"
        # pod templates must not smuggle one in either
        template = doc.get("spec", {}).get("template", {}) or doc.get("spec", {}).get("jobTemplate", {})
        assert "namespace" not in template.get("metadata", {})


def test_no_pronounce_configmap_is_committed():
    assert not [d for d in _all_docs() if d["kind"] == "ConfigMap"], "ConfigMap is generated by DEPLOY.md, not committed"
    assert not list(DEPLOY.glob("*pronounce*")) and not list(DEPLOY.glob("*configmap*"))


def test_deployment_shape(deployment):
    spec = deployment["spec"]
    assert spec["replicas"] == 1
    assert spec["strategy"]["type"] == "Recreate"
    pod = spec["template"]["spec"]
    assert pod["securityContext"]["runAsNonRoot"] is True
    assert pod["securityContext"]["runAsUser"] == 1000
    assert pod["securityContext"]["fsGroup"] == 1000


def test_deployment_resources_and_security(container):
    res = container["resources"]
    assert res["requests"] == {"cpu": "500m", "memory": "1Gi"}
    assert res["limits"] == {"cpu": "1500m", "memory": "2Gi"}
    sc = container["securityContext"]
    assert sc["allowPrivilegeEscalation"] is False
    assert sc["readOnlyRootFilesystem"] is True
    assert container["imagePullPolicy"] == "IfNotPresent"
    image = container["image"]
    assert image.startswith("kick-tts:") and not image.endswith(":latest")


def test_deployment_env(container):
    env = _env(container)
    for name in ("OMP_NUM_THREADS", "MKL_NUM_THREADS", "TORCH_NUM_THREADS"):
        assert env.get(name) == "2", f"{name} must be the string \"2\""
    assert env["HF_HUB_OFFLINE"] == "1"
    assert env["PRONOUNCE_PATH"] == "/config/pronounce.yaml"
    assert any(e.get("secretRef", {}).get("name") == "kick-tts-secrets" for e in container["envFrom"])


def test_deployment_volumes_and_cache_env(deployment, container):
    pod = deployment["spec"]["template"]["spec"]
    mounts = {m["name"]: m for m in container["volumeMounts"]}
    volumes = {v["name"]: v for v in pod["volumes"]}

    assert mounts["cache"]["mountPath"] == "/cache"
    assert _env(container)["XDG_CACHE_HOME"] == "/cache" == mounts["cache"]["mountPath"]
    assert volumes["cache"]["persistentVolumeClaim"]["claimName"] == _one("pvc.yaml", "PersistentVolumeClaim")["metadata"]["name"]

    assert mounts["config"]["mountPath"] == "/config"
    assert volumes["config"]["configMap"]["name"] == "kick-tts-pronounce"

    # read-only root filesystem needs a writable /tmp
    assert mounts["tmp"]["mountPath"] == "/tmp"
    assert "emptyDir" in volumes["tmp"]


def test_deployment_probes(container):
    port = next(p for p in container["ports"] if p["name"] == "http")
    assert port["containerPort"] == 8000

    startup = container["startupProbe"]
    assert startup["httpGet"]["path"] == "/readyz"
    assert startup["periodSeconds"] == 5
    assert startup["failureThreshold"] == 60
    assert container["readinessProbe"]["httpGet"]["path"] == "/readyz"
    assert container["livenessProbe"]["httpGet"]["path"] == "/healthz"
    for probe in (startup, container["readinessProbe"], container["livenessProbe"]):
        assert probe["httpGet"]["port"] == "http"


def test_service():
    svc = _one("service.yaml", "Service")
    (port,) = svc["spec"]["ports"]
    assert port["name"] == "http" and port["port"] == 80 and port["targetPort"] == "http"
    pod_labels = _one("deployment.yaml", "Deployment")["spec"]["template"]["metadata"]["labels"]
    assert svc["spec"]["selector"].items() <= pod_labels.items()


def test_ingress_matches_steam_overlay_pattern():
    ing = _one("ingress.yaml", "Ingress")
    assert ing["metadata"]["annotations"] == {
        "cert-manager.io/cluster-issuer": "letsencrypt-prod",
        "nginx.ingress.kubernetes.io/force-ssl-redirect": "true",
        "nginx.ingress.kubernetes.io/ssl-redirect": "true",
        "nginx.ingress.kubernetes.io/proxy-read-timeout": "3600",
        "nginx.ingress.kubernetes.io/proxy-send-timeout": "3600",
        "nginx.ingress.kubernetes.io/rewrite-target": "/$2",
    }
    spec = ing["spec"]
    assert spec["ingressClassName"] == "nginx"
    (rule,) = spec["rules"]
    assert rule["host"] == "anildev.io"
    (path,) = rule["http"]["paths"]
    assert path["path"] == "/tts(/|$)(.*)"
    assert path["pathType"] == "ImplementationSpecific"
    backend = path["backend"]["service"]
    assert backend["name"] == _one("service.yaml", "Service")["metadata"]["name"]
    assert backend["port"]["number"] == 80
    assert spec["tls"] == [{"hosts": ["anildev.io"], "secretName": "anildev-tls"}]


def test_pvc():
    pvc = _one("pvc.yaml", "PersistentVolumeClaim")
    assert pvc["spec"]["storageClassName"] == "local-path"
    assert pvc["spec"]["accessModes"] == ["ReadWriteOnce"]
    assert pvc["spec"]["resources"]["requests"]["storage"] == "1Gi"


def test_secret_example_has_only_placeholders():
    secret = _one("secret.example.yaml", "Secret")
    assert secret["metadata"]["name"] == "kick-tts-secrets"
    data = secret["stringData"]
    assert set(data) == {
        "CONTROL_TOKEN", "OVERLAY_KEY", "ANTHROPIC_API_KEY",
        "KICK_CLIENT_ID", "KICK_CLIENT_SECRET", "KICK_BROADCASTER_USER_ID",
    }
    for key, value in data.items():
        assert value in ("CHANGE_ME", "0"), f"{key} must be a placeholder"
    assert data["KICK_BROADCASTER_USER_ID"] == "0"  # int setting: must stay parseable


def test_servicemonitor_targets_the_service():
    sm = _one("servicemonitor.yaml", "ServiceMonitor")
    svc = _one("service.yaml", "Service")
    assert sm["metadata"]["labels"]["release"] == "CHANGE_ME"
    assert sm["spec"]["selector"]["matchLabels"].items() <= svc["metadata"]["labels"].items()
    (endpoint,) = sm["spec"]["endpoints"]
    assert endpoint["port"] == "http"
    assert endpoint["path"] == "/metrics"
    assert endpoint["interval"] == "30s"
    text = (DEPLOY / "servicemonitor.yaml").read_text(encoding="utf-8")
    assert "serviceMonitorSelector" in text  # discovery command documented in the file


def test_cronjob():
    cj = _one("cronjob.yaml", "CronJob")
    assert cj["spec"]["schedule"] == "0 */6 * * *"
    assert cj["spec"]["concurrencyPolicy"] == "Forbid"
    pod = cj["spec"]["jobTemplate"]["spec"]["template"]["spec"]
    assert pod["securityContext"]["runAsNonRoot"] is True
    (c,) = pod["containers"]
    assert c["command"] == ["python", "scripts/kick_subscribe.py", "ensure"]
    assert c["image"] == _one("deployment.yaml", "Deployment")["spec"]["template"]["spec"]["containers"][0]["image"]
    assert any(e.get("secretRef", {}).get("name") == "kick-tts-secrets" for e in c["envFrom"])
    assert c["resources"]["limits"]["memory"] and c["resources"]["requests"]["cpu"]


# --------------------------------------------------------------------------- Dockerfile

@pytest.fixture(scope="module")
def dockerfile() -> str:
    return (ROOT / "Dockerfile").read_text(encoding="utf-8")


def test_dockerfile_args_and_torch_install(dockerfile):
    assert re.search(r"^ARG TORCH_VERSION=2\.14\.1$", dockerfile, re.M)
    assert re.search(r"^ARG EMA_REVISION$", dockerfile, re.M)
    assert "https://download.pytorch.org/whl/cpu" in dockerfile
    assert "torch==${TORCH_VERSION}" in dockerfile
    assert "-r requirements.txt" in dockerfile
    assert "fetch_weights.py --revision" in dockerfile and "--lock weights.lock.json" in dockerfile
    assert re.search(r'-z "\$\{EMA_REVISION\}"', dockerfile), "build must fail when EMA_REVISION is empty"
    assert "FROM python:3.12-slim" in dockerfile


def test_dockerfile_has_no_torchaudio_or_torchvision(dockerfile):
    assert "torchaudio" not in dockerfile.lower()
    assert "torchvision" not in dockerfile.lower()


def test_dockerfile_runtime_env_and_user(dockerfile):
    runtime = dockerfile.split("AS runtime", 1)[1]
    for expected in (
        "HF_HUB_OFFLINE=1", "OMP_NUM_THREADS=2", "MKL_NUM_THREADS=2", "TORCH_NUM_THREADS=2",
        "EMA_WEIGHTS_DIR=/opt/weights", "XDG_CACHE_HOME=/cache", "PYTHONUNBUFFERED=1",
    ):
        assert expected in runtime, expected
    users = re.findall(r"^USER\s+(\S+)", dockerfile, re.M)
    assert users, "no USER instruction"
    assert users[-1].split(":")[0] not in ("root", "0")
    assert "EXPOSE 8000" in dockerfile
    cmd = re.search(r"^CMD (\[.*\])$", dockerfile, re.M)
    assert cmd and '"--workers", "1"' in cmd.group(1) and '"--proxy-headers"' in cmd.group(1)
    assert '"app.main:app"' in cmd.group(1)
    # the last stage must not install packages as root at runtime
    assert "pip install" not in runtime


def test_requirements_do_not_list_torch():
    names = [
        re.split(r"[=<>\[ ]", line.strip(), maxsplit=1)[0].lower()
        for line in (ROOT / "requirements.txt").read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    ]
    assert not {"torch", "torchaudio", "torchvision"} & set(names)


def test_dockerignore_excludes_secrets_and_bulk():
    lines = {
        ln.strip() for ln in (ROOT / ".dockerignore").read_text(encoding="utf-8").splitlines()
        if ln.strip() and not ln.startswith("#")
    }
    assert {".venv/", ".git/", "tests/", "docs/*.wav", ".env", "weights/"} <= lines


# --------------------------------------------------------------------------- secrets / docs

_SECRET_PATTERNS = [
    re.compile(r"sk-ant-"),
    re.compile(r"\bsk-[A-Za-z0-9]{20,}"),
    re.compile(r"\b[0-9a-fA-F]{32,}\b"),  # hex blobs (sha256, tokens)
    # long base64 / token-looking strings that mix letters and digits
    re.compile(r"(?=[A-Za-z0-9+/=_-]*\d)(?=[A-Za-z0-9+/=_-]*[A-Za-z])[A-Za-z0-9+/=_-]{32,}"),
]


@pytest.mark.parametrize(
    "path",
    [*sorted(DEPLOY.glob("*.yaml")), ROOT / "Dockerfile", ROOT / "docs" / "DEPLOY.md"],
    ids=lambda p: p.name,
)
def test_no_real_looking_secrets(path: Path):
    text = path.read_text(encoding="utf-8")
    for pattern in _SECRET_PATTERNS:
        match = pattern.search(text)
        assert match is None, f"{path.name}: looks like a credential: {match.group(0)[:12]}..."


def test_secret_scan_patterns_catch_real_looking_values():
    # guard against the scanner silently matching nothing
    samples = ["sk-ant-api03-abcdef", "0123456789abcdef0123456789abcdef", "Zm9vYmFyMTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3A="]
    for sample in samples:
        assert any(p.search(sample) for p in _SECRET_PATTERNS), sample


def test_deploy_doc_covers_required_steps():
    doc = (ROOT / "docs" / "DEPLOY.md").read_text(encoding="utf-8")
    for needle in (
        "fetch_weights.py --revision <sha> --out weights --write-lock",
        "docker build --build-arg EMA_REVISION=<sha> -t kick-tts:<tag> .",
        "docker save kick-tts:<tag> | sudo k3s ctr images import -",
        "kubectl create configmap kick-tts-pronounce --from-file=pronounce.yaml=app/reader/pronounce.yaml -n streaming --dry-run=client -o yaml | kubectl apply -f -",
        "kubectl get prometheus -n monitoring -o yaml | grep -A5 serviceMonitorSelector",
        "kubectl get certificate -n streaming",
        "https://anildev.io/tts/healthz",
        "503",
        "torch",
        "2.14.1",
        "ema-lightning",
        "rollout restart",
        "rollout undo",
        "VmRSS",
        "kubectl apply -n streaming -f deploy/cronjob.yaml",
        "kubectl set image cronjob/kick-tts-subscribe",
    ):
        assert needle in doc, needle
    # apply order: pvc, configmap, secret, deployment, service, ingress, servicemonitor, cronjob
    # (the ConfigMap is created by a pipe command shown just before this block, so it is not in the list)
    order = [
        "-f deploy/pvc.yaml", "-f deploy/secret.local.yaml", "-f deploy/deployment.yaml",
        "-f deploy/service.yaml", "-f deploy/ingress.yaml", "-f deploy/servicemonitor.yaml",
        "-f deploy/cronjob.yaml",
    ]
    apply_section = doc.split("## 4. Apply", 1)[1].split("### ServiceMonitor selector", 1)[0]
    positions = [apply_section.index(item) for item in order]
    assert positions == sorted(positions)
